### ISSUE TITLE
no need async

### ISSUE THREAD

**Issue by superwf** [panmenglin/tenon-webpack-plugin#1]
https://github.com/panmenglin/tenon-webpack-plugin/blob/ff66f889bd23cffd04a9e1c48a6affe02ca39f12/src/tenon-webpack-plugin.ts#L19
For keep simple, here no async operation, so I think only use tap is ok.

**Comment by panmenglin** [comment]
You're right. I have replaced tapAsync with tap in version `1.0.5`.
